/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package desingera.vista;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Daniela
 */
public class Pantalla_DesingEra extends javax.swing.JFrame {

    /**
     * Creates new form Vista_DesingEra
     * Es el método vista del proyecto
     */
    public Pantalla_DesingEra() {
        initComponents();
        setTitle("DesingEra");
        //this.setIconImage( new ImageIcon(getClass().getResource("/desingera/diseño/logo2.png")).getImage() );
        System.out.println("Lanzando la ventana con el logo");
        ajustarImagen();
        setSize(600, 600);
        this.setLocationRelativeTo(null);
        setResizable(false); // Evita que la ventana se redimensione
        
     // Crear un temporizador que cierre la ventana después de 5 segundos (5000 milisegundos)
        Timer timer = new Timer(5000, e -> {
        dispose(); // Cierra la ventana actual
        System.out.println("Ventana cerrada automáticamente."); // Mensaje opcional
        
        // Abrir la ventana de Login
            System.out.println("Abriendo nueva ventana.......con el login");
            Login VentanaLogin = new Login(); // Crear una instancia de Login
            VentanaLogin.setVisible(true);   // Mostrar la ventana de Login
        });

        timer.setRepeats(false); // El temporizador solo se ejecuta una vez
        timer.start(); // Inicia el temporizador
    }

    
    
    private void ajustarImagen() {
        // Cargar la imagen desde la carpeta "desingera.diseño" en tu proyecto
        ImageIcon icono = new ImageIcon(getClass().getResource("/desingera/diseño/logo2.png"));
        
        // Especificar tamaño mediano (ancho y alto) de la imagen
            int ancho = 600; // Ancho deseado
            int alto = 600;  // Alto deseado

        // Escalar la imagen al tamaño mediano
            Image imagenEscalada = icono.getImage().getScaledInstance(
            ancho, alto, Image.SCALE_SMOOTH
            );
        
        // Poner la imagen escalada en el JLabel
        jLabel1.setIcon(new ImageIcon(imagenEscalada));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desingera/diseño/logo2.png"))); // NOI18N
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
