/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package desingera.vista;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author daniela
 */
public class Principal_DesingEra extends javax.swing.JFrame {

    /**
     * Constructor de la clase Principal_DesingEra.
     * Inicializa los componentes gráficos, establece el tamaño y posición de la ventana,
     * y añade los listeners para los botones.
     */
    public Principal_DesingEra() {
        initComponents();
        setBounds(0,0,600,600);
        setLocationRelativeTo(null); // Centrar la ventana
        
     
        btnSala.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("---> Sala de estar");
                mostrarImagen("/desingera/diseño/salon1.jpg");
            }
        });

        btnCocinaa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("---> Cocina");
                mostrarImagen("/desingera/diseño/cocina1.jpg");
            }
        });

        btnHabitacion.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("---> Habitaciones");
                mostrarImagen("/desingera/diseño/habit1.jpg");
            }
        });

        btnBañoo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("---> Baño");
                mostrarImagen("/desingera/diseño/baño1.jpg");
            }
        });
        
         btnConfig.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("---> Configuración");
                abrirVentanaConfiguracion();
            }
        });
         
       
    }

    
          
    // Método para mostrar la imagen en el JLabel
    private void mostrarImagen(String rutaImagen) {
        ImageIcon icono = new ImageIcon(getClass().getResource(rutaImagen));
        Image imagen = icono.getImage().getScaledInstance(LabelFotos.getWidth(), LabelFotos.getHeight(), Image.SCALE_SMOOTH);
        LabelFotos.setIcon(new ImageIcon(imagen));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnSala = new javax.swing.JButton();
        btnCocinaa = new javax.swing.JButton();
        btnHabitacion = new javax.swing.JButton();
        btnBañoo = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        btnConfig = new javax.swing.JButton();
        LabelFotos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 103, 41));

        jPanel1.setBackground(new java.awt.Color(0, 103, 41));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBackground(new java.awt.Color(0, 103, 41));
        jToolBar1.setRollover(true);

        btnSala.setText("Sala de Estar");
        btnSala.setFocusable(false);
        btnSala.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSala.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSala);

        btnCocinaa.setText("Cocina");
        btnCocinaa.setFocusable(false);
        btnCocinaa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCocinaa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCocinaa);

        btnHabitacion.setText("Habitaciones");
        btnHabitacion.setFocusable(false);
        btnHabitacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHabitacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnHabitacion);

        btnBañoo.setText("Cuarto de Baño");
        btnBañoo.setFocusable(false);
        btnBañoo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBañoo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnBañoo);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jToolBar2.setRollover(true);

        btnConfig.setText("Configuración");
        btnConfig.setFocusable(false);
        btnConfig.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfig.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnConfig);

        jPanel1.add(jToolBar2, java.awt.BorderLayout.PAGE_END);
        jPanel1.add(LabelFotos, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que abre la ventana de configuración.
     * Utiliza un JDialog para mostrar una ventana secundaria modal.
     */
     
    private void abrirVentanaConfiguracion() {
    // Crear una instancia de la ventana JDialog
    VentanaConfig_DesingEra ventanaConfig = new VentanaConfig_DesingEra(this, true);
    
    // Hacerla visible
    ventanaConfig.setVisible(true);
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFotos;
    private javax.swing.JButton btnBañoo;
    private javax.swing.JButton btnCocinaa;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnHabitacion;
    private javax.swing.JButton btnSala;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
